name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todos os dias à meia-noite UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist
